# Generated by Django 3.2.9 on 2021-11-07 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('comedian', 'comedian'), ('pro', 'pro'), ('amatuer', 'amatuer'), ('roaster', 'roaster'), ('spectator', 'spectator')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('haha', 'Funny'), ('ohhh', 'amazed'), ('nahh', 'Not Funny')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('stage', models.CharField(choices=[('special', 'special'), ('Far', 'Far'), ('Very close', 'close'), ('to be roasted', 'tobe')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('bio', models.CharField(max_length=250)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='core.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('caption', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='jokes_photo/')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('time_posted', models.TimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comment')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacted', to='core.reaction')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.roast')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreact', to='core.reaction'),
        ),
    ]
