# Generated by Django 3.2.9 on 2021-11-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_level_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/jokes_photo/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profiles/'),
        ),
    ]
