# Generated by Django 3.2.9 on 2021-11-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211107_0234'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='profile',
        ),
    ]
